name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  validation-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflow-templates/setup.yml
    
    - name: Run validation checks
      working-directory: .
      run: rebar3 do xref, dialyzer
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflow-templates/setup.yml

    - name: Check that the release can be built
      working-directory: .
      run: rebar3 do release, tar

  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflow-templates/setup.yml

    - name: Run unit tests
      working-directory: .
      run: |
        mkdir results
        rebar3 do ct --dir apps --verbose true --logdir ./results --label erlang-ci --cover true, cover -v
    
    - name: Upload test results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: erlang-ci-results
        path: ./results
        compression-level: 9
        retention-days: 30
    
    - name: Publish Erlang CI results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: Erlang CI results
        files: |
          ./results/**/*.xml
