name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:26.1.2

    steps:
    - uses: actions/checkout@v4
    - name: Run validation checks
      working-directory: .
      run: rebar3 check
    - name: Run unit tests
      working-directory: .
      run: |
        mkdir results
        rebar3 ct --dir apps --verbose true --logdir ./results --label erlang-ci --cover true
    - name: Release can be built
      working-directory: .
      run: rebar3 do release, tar
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: erlang-ci-results
        path: ./results
        compression-level: 9
        retention-days: 30
    - name: Erlang CI results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: Erlang CI results
        files: |
          ./results/**/*.xml

    # - name: Publish HTML report to Github pages
    #   if: always()
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     publish_dir: ./results/last
    #     destination_dir: ./tests/erlang-ci/${{ github.run_number }} # This is where index.html will be output
    #     keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub 
        
    - name: Publish HTML report to Github pages
      uses: PavanMudigonda/html-reporter-github-pages@v1.2
      with:
        test_results: ./results/last
        keep_reports: 20
        subfolder: tests  # Level 1 Folder
        tool_name: common_test # Level 2 Folder
        workflow_name: ${{ github.workflow }} # Level 3 Folder
        env: ${{ github.run_number }} # Level 4 Folder
      
