name: Relup CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  RELNAME: pixelwar

jobs:
  versions:
    runs-on: ubuntu-latest

    container:
      image: ahzed11/erlang25-dind:latest
      options: "--privileged"

    steps:
    - name: Check if we have tags
      id: check
      uses: ahzed11/has-tags-action@v1.1

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run validation checks and build releases
      working-directory: erlang
      if: ${{steps.check.outputs.hasTags == 'true'}}
      run: |
        ../scripts/check_versions $(/usr/bin/git log -1 --format='%H') > vsn.log
        cat vsn.log
        cat vsn.log | awk '/Generated appup/ { appup=1 }
                           /relup successfully created!/ { relup=1 }
                           END { if (!appup) { print "appup missing"; exit 1}
                                 if (!relup) { print "relup missing"; exit 1} }'
        OLD=$(cat vsn.log | awk '/OLD:/ {print $2}')
        NEW=$(cat vsn.log | awk '/NEW:/ {print $2}')
        echo "OLD_TAR=$OLD" >> $GITHUB_ENV
        echo "NEW_TAR=$NEW" >> $GITHUB_ENV

      
    - name: Run relup application
      working-directory: erlang
      if: ${{steps.check.outputs.hasTags == 'true'}}
      run: |
        mkdir relupci
        mkdir relupci/releases/
        cp "${{ env.OLD_TAR }}" relupci/releases/
        cp "${{ env.NEW_TAR }}" relupci/releases/

        OLD_TAG=$(echo "${{ env.OLD_TAR }}"  | sed -nr 's/^.*([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz$/\1/p')
        NEW_TAG=$(echo "${{ env.NEW_TAR }}"  | sed -nr 's/^.*([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz$/\1/p')

        echo -e "{old_version, \"$OLD_TAG\"}.\n{new_version, \"$NEW_TAG\"}.\n{release_name, \"$RELNAME\"}.\n{release_dir, \"/__w/$RELNAME/$RELNAME/erlang/relupci/releases/\"}." >> ./test/config.config
        cat ./test/config.config

        cd test
        ls
        mkdir results
        rebar3 ct --dir . --verbose true --config ./config.config --logdir ./results --label relup-ci

        status=$?
        [ $status -ne 0 ] && exit 1

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: results
        path: ./erlang/test/results
        retention-days: 1
